<<<<<<< HEAD
#Volumes Persistentes:
# persistent-volume.yaml
=======
>>>>>>> c3b670c (Arquivos aplicacao)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
<<<<<<< HEAD
      storage: 10Gi
=======
      storage: 10Gi
>>>>>>> c3b670c (Arquivos aplicacao)
